version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smartcampus-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartcampus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smartcampus-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/smartcampus
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: smartcampus-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data:
